name: Build Linux (musl) binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Install musl tools
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build (static musl)
        run: |
          RUSTFLAGS="-C target-feature=+crt-static" \
          cargo build --release --target x86_64-unknown-linux-musl
          ls -lah target/x86_64-unknown-linux-musl/release/

      - name: Make executable
        run: chmod +x target/x86_64-unknown-linux-musl/release/rust-uesave

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-uesave-linux-musl
          path: target/x86_64-unknown-linux-musl/release/rust-uesave
